name: Deploy to GitHub Pages

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run build
      - run: npm install -g gh-pages
      - run: gh-pages -d build
      - uses: actions/create-deployment@v1
        with:
          deployment_environment: production
          environment_url: https://maddes.github.io/team-skills
